### PR TITLE
Fixed folding bug that prevented observations from showing

### LINKED ISSUE #612: Can't make observations in Garnet
Form appears to be there, but section won't expand.

Image is of after having clicked on section header.

screen shot 2016-05-25 at 4 53 25 pm

### PR DESCRIPTION
**Pull request by RobertAKARobin**
Fixes #612

### CODE REVIEW

File: app/assets/javascripts/nav.js [hunk 1]
```diff
@@ -47,17 +47,17 @@ $(function() {
...
+  //     $("html, body").animate({
+  //       scrollTop: 0
+  //     }, 500);
+  //   } else if ( $( $(this).attr('href') ) ) {
+  //     $('html, body').animate({
+  //       scrollTop: $( $(this).attr('href') ).offset().top - navHeight
+  //     }, 500);
+  //   }
+  //   return false;
+  // });
```
Comment (jshawl) [inline app/assets/javascripts/nav.js]: nooooooooooooooo

**Comment by RobertAKARobin** [comment]
@jshawl Fine, fine. Fixed your way.
